name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: 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
#       //ACCESS_TOKEN 是生成的token名称，注意换成自己的
        TARGET_REPO: ChelFannie/chelFannie.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: dosc/.vuepress/dist/
#       //这里目录指向生成物目录
